### ISSUE TITLE
question about RCV1 tokenization

### ISSUE THREAD

**Issue by cjlin1** [yu54ku/xml-cnn#2]
On the home page you stated that "Caution: This dataset is tokenized
differently than the one used by Liu et al."
May I ask more details about this?
Does this mean Liu et al. didn't use tokens provided at
the RCV1 page?
Thanks

**Comment by yu54ku** [comment]
Hello! Thank you for your issue.

I'll answer the question you asked.
I think your answer is correct.
However, this is not accurate, and the reasons given below are correct.

Liu's argument is as follows.
- In the experiments of Liu et al.
- They used the vector of TF-IDF features for the non-deep learning method.
- They used the raw text of the document obtained from the author of the repository for the deep learning method.
- They removed words that don't have corresponding TF-IDF features from the raw text.
- Because they wanted to use datasets with the same conditions for non-deep learning and deep learning. 

For these reasons, I think they were using a somewhat different dataset than Lewis at el.
