### ISSUE TITLE
Load large dataset.

### ISSUE THREAD

**Issue by nikomylo** [yu54ku/xml-cnn#5]
Hello and thank you for this implementation.

I would like to ask if there is a way to load the data in batches since my dataset is quite large (50 GB) and cannot fit into the memory.

**Comment by yu54ku** [comment]
Hello! Thank you for your issue.

If you want to do that, I think you need to make your own Pytorch's dataloader.
Because this program uses functions, which is included in torchtext.
I don't think torchtext's functions had the feature to split and load data.

I would really like to implement and publish this dataloader, but unfortunately I don't have a Linux machine with GPUs now...
Can you challenge yourself on this?

This is all the support I can give you.
I'm sorry I can't help you.

If you have any other questions, please create issues!
Thanks.

**Comment by nikomylo** [comment]
Thank you very much for your reply, i will look into it !
